spring.application.name=backend_java
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=false
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
server.port=8081

# AI Inference Backend
ai.worker.url=http://localhost:8080
